#Range: 0.0 ~ 100.0
m67_explosive_damage = 26.0
#Range: 0.0 ~ 30.0
m67_explosive_range = 3.0
# 
# 
#Range: 0.0 ~ 50.0
m116a1_flash_range = 5.0
#Range: 0 ~ 200
m116a1_flash_duration = 80
# 
# 
#Range: 0.0 ~ 100.0
mk3a2_explosive_damage = 26.0
#Range: 0.0 ~ 50.0
mk3a2_explosive_range = 2.0
#Range: 0.0 ~ 30.0
mk3a2_flash_range = 2.0
#Range: 0 ~ 200
mk3a2_flash_duration = 60
# 
# 
#Range: 0.0 ~ 100.0
m202_explosive_damage = 34.0
#Range: 0.0 ~ 30.0
m202_explosive_range = 6.0
# 
# 
#Range: 0.0 ~ 100.0
gm94_explosive_damage = 28.0
#Range: 0.0 ~ 30.0
gm94_explosive_range = 5.0
# 
# 
is_ammo_kit_supplier_craftable = false
explosion_destroys_entities = false
#0: None, 1: Glass Material Only, 2: All Blocks
#Range: 0 ~ 2
explosion_destruction_type = 0
#Ticks of binoculars' range detecting update interval, lower values might cause lags
#Range: 0 ~ 40
binocular_update_interval = 4
#Multiplier for the damage caused by all ava damage source
#Range: 0.0 ~ 40.0
damage_multiplier_against_players = 2.0
#Range: 0.0 ~ 40.0
damage_multiplier_against_others = 1.0
should_guards_spawn = false
#Range: 0 ~ 100
guards_spawn_chance = 50
# 
# 
#https://docs.google.com/document/d/1950eqPMlePlyoeaFH1_MRRBRw5nishlXjR3h9FkDIhE/edit?usp=sharing
#Whether guns like m24 and mosin-nagant can be used
enable_snipers = true
#Whether guns like sr-25 can be used
enable_semi_snipers = true
#Whether guns like mk20 can be used
enable_rifles = true
#Whether guns like mp5k and x95r can be used
enable_sub_machineguns = true
#Whether guns like remington870 can be used
enable_shotguns = true
#Whether guns like p226 can be used
enable_pistols = true
#Whether guns like N/A can be used
enable_auto_pistols = true
#Whether projectiles like m67 and m18 can be used
enable_projectiles = true
#Whether special weapons like gm94 and m202 can be used
enable_special_weapons = true
# 
# 
# 
# 
# 
#Set both to true to enable competitive mode, please make sure you know what it isbefore setting it to true
enable_competitive_mode = false
enable_competitive_mode_confirm = false
preset_with_parachute = false
# 
# 
# 
#Disabled items. Format: m18_toxic, m202, gm94
disabled_weapons = ""
# 
# 
# 
#Range: 0.0 ~ 1.0
field_knife_movement_speed_bonus = 0.0035
# 
# 
#Whether there should be a delay while drawing a weapon
weapon_drawing_delay = true
# 
# 
team_spawn_restriction = true

